export const CONSTANT_TYPE_JOURNEYS = {
    HYBIRD_CAR: 'HYBIRD_CAR',
    COACH_CAR: 'COACH_CAR'
}
export const CONSTANT_TYPE_BOOKING = {
    HYBIRD_CAR: 'HYBIRD_CAR',
    COACH_CAR: 'COACH_CAR',
    HYBIRD_DELIVERY_CAR: 'HYBIRD_DELIVERY_CAR',
    COACH_DELIVERY_CAR: 'COACH_DELIVERY_CAR'
}