const stringVi = {
  language: 'vi',
  SharePlaneSaga: {
    txt_error_pick: 'Lựa chọn điểm đi và điểm đón không phù hợp. Vui lòng chọn lại',
  },
  UserProfileSaga: {
    txt_acount_lock: 'Tài khoản của bạn đã bị khoá. Vui lòng liên hệ tổng đài để được hỗ trợ thêm',
    txt_comfirm: 'Đồng ý',
    txt_update_success: 'Cập nhật thành công',
  },
  HistorySaga: {
    txt_cancel_trip_success: 'Huỷ chuyến thành công',
    txt_send_complain_success: 'Gửi khiếu nại thành công',
  },
  HandleErrorCode: {
    txt_haveTrip: 'Bạn đang thực hiện một chuyến đi khác. Vui lòng đặt lại khi chuyến đi kết thúc',
    txt_unknow_error: 'Đã có lỗi xảy ra (unknow error)',
    txt_param_error: 'Đã có lỗi xảy ra (Parram error)',
    txt_data_nil: 'Không có dữ liệu',
    txt_request_fail: 'Yêu cầu thất bại vui lòng thử lại',
    txt_not_enough_money: 'Bạn không có đủ số dư điểm để thực hiện yêu cầu này',
    txt_account_not_exsist: 'Tài khoản này không tồn tại',
    txt_system_error: 'Lỗi hệ thống vui lòng thử lại sau',
    txt_session_expired: 'Phiên đăng nhập đã hết hạn vui lòng đăng nhập lại',
  },
  PlanItem: {
    txt_finding: 'Tìm yêu cầu phù hợp',
    txt_cancel_plan: 'Huỷ chia sẻ',
    txt_show_detail: 'Xem chi tiết',
    txt_share: 'Bạn đang chia sẻ chuyến đi',
  },
  HistoryItem: {
    txt_trip_cancel: ' Chuyến đã huỷ',
    txt_find_driver: ' Tìm tài xế',
    txt_driver_pick_up: ' Tài xế đang đến đón bạn',
    txt_passenger_wait: ' Hành khách đang đợi bạn đến đón',
    txt_running: ' Chuyến đang chạy',
    txt_trip_finished: ' Chuyến đi đã kết thúc',
    txt_point: 'Điểm',
    txt_share: 'Chia sẻ',
    txt_hitchhike: 'Đi nhờ',
  },
  CreateTrip: {
    txt_select_origin: 'Lựa chọn điểm đón',
    txt_input_origin: 'Nhập điểm đón . . . ',
    txt_select_with_map: 'Chọn bằng bản đồ',
    txt_put_origin: 'Đặt điểm đón',
    txt_put_destination: 'Đặt điểm đến',
    txt_input_destination: 'Nhập điểm đến . . . ',
    txt_origin: 'Điểm đón',
    txt_destination: 'Điểm đến',
    txt_point_to_usage: 'Điểm cần sử dụng',
    txt_point: 'Điểm',
    txt_find_driver: 'Tìm tài xế',
    txt_ask_where_go: 'Bạn muốn đi đến đâu?',
  },
  DetailTripScreen: {
    txt_top_bar_title: 'Thông tin chi tiết',
    txt_cancel_trip: 'Bạn có chắc chắn muốn huỷ chuyến đi này?',
    txt_cancel: 'Không',
    txt_comfirm: 'Đồng ý',
    txt_cancel_trip_noDriver: 'Bạn có chắc chắn muốn gửi báo cáo này?',
    txt_passenger_cancel: 'Hành khách yêu cầu huỷ chuyến',
    txt_Driver_busy: 'Tôi có việc bận không thể đến đón khách được',
    txt_other_reason: 'Lý do khác',
    txt_Driver_cancel: 'Tài xế báo huỷ',
    txt_Passenger_no_need: 'Tôi không có nhu cầu đi nữa',
    txt_origin: 'Điểm đón',
    txt_destination: 'Điểm đến',
    txt_detail_trip: 'Chi tiết chuyến',
    txt_trip_thanks: '(Chuyến đi nhờ)',
    txt_sharing_trip: '(Chuyến chia sẻ)',
    txt_point_usage: 'Điểm sử dụng',
    txt_point: 'Điểm',
    txt_distance: 'Khoảng cách',
    txt_find_sharers: '. . . Đang tìm người chia sẻ',
    txt_cancel_trip_act: 'Huỷ chuyến',
    txt_trip_was_cancel: 'Chuyến đi này đã bị huỷ',
    txt_agree: 'đã đồng ý cho bạn đi nhờ. Người chia sẻ sẽ liên lạc với bạn sau ít phút',
    txt_name: 'Họ tên',
    txt_phone: 'Số điện thoại',
    txt_liecense_plate: 'Biển số xe',
    txt_agree_to: 'Bạn đã đồng ý cho',
    txt_hitchhike: 'đi nhờ',
    txt_take_passenger: 'Đón khách',
    txt_trip_was_finish: 'Chuyến đi này đã kết thúc',
    txt_report: 'Báo cáo chuyến đi',
    txt_finishTrip: 'Trả khách',
    txt_shared_a_trip: 'đã chia sẻ chuyến đi với bạn',
    txt_running_with: 'Bạn đang thực hiện chuyến đi cùng',
    txt_send_complain: 'Gửi khiếu nại',
    txt_content: 'Nội dung',
    txt_reason: 'Lí do huỷ chuyến',
    txt_place_holder_reason: 'Chọn lý do huỷ chuyến . . .',
    txt_request_cancel_trip: 'Yêu cầu huỷ chuyến',
  },
  DetailUserProfileScreen: {
    txt_top_bar_title: 'Thông tin tài khoản',
    txt_point: 'Điểm',
    txt_name: 'Họ tên',
    txt_phone: 'Số điện thoại',
    txt_liecense_plate: 'Biển số xe',
    txt_vehicle_name: 'Tên xe',
    txt_save: 'Lưu thông tin',
    txt_camera: 'Máy ảnh',
    txt_library: 'Chọn từ thư viện',
    txt_cancel: 'Huỷ bỏ',
  },
  HistoryScreen: {
    txt_top_bar_title: 'Lịch sử ',
    txt_empty: 'Bạn chưa đặt chuyến đi nào',
  },
  PendingTripScreen: {
    txt_top_bar_title: 'Bạn có muốn nhận chuyến đi này?',
    txt_ask: 'Bạn có chắc chắn muốn chia sẻ chuyến đi với người này?',
    txt_comfirm: 'Đồng ý',
    txt_cancel: 'Không',
    txt_time: 'Thời gian',
    txt_name: 'Họ tên:',
    txt_distance: 'Quãng đường:',
    txt_point_take: 'Điểm nhận về:',
    txt_point: 'Điểm',
    txt_take_trip: 'Nhận chuyến',
    txt_later: 'Để sau',
    txt_trip_has_driver: 'Chuyến đi này đã có người khác nhận',
    txt_trip_cancel: 'Chuyến đi này đã bị huỷ',
    txt_trip_finish: 'Chuyến đi này đã kết thúc',
  },
  SearchTripSceen: {
    txt_top_bar_title: 'Tìm kiếm yêu cầu',
    txt_finding: 'Đang tìm kiếm chuyến đi phù hợp . . .',
  },
  SharePlanScreen: {
    txt_infomation_about_car: 'Bạn chưa có thông tin về xe. Vui lòng cập nhật tại đây',
    txt_update: 'Cập nhật ngay',
    txt_later: 'Để sau',
    txt_select_origin: 'Lựa chọn điểm đón',
    txt_input_origin: 'Nhập điểm đón . . . ',
    txt_select_with_map: 'Chọn bằng bản đồ',
    txt_put_origin: 'Đặt điểm xuất phát',
    txt_put_destination: 'Đặt điểm đến',
    txt_select_destination: 'Lựa chọn điểm đến',
    txt_input_destination: 'Nhập điểm đến . . . ',
    txt_title_step_comfirm: 'Green-Move',
    txt_origin: 'Điểm xuất phát',
    txt_destination: 'Điểm đến',
    txt_point_to_use: 'Số điểm nhận về',
    txt_point: 'Điểm',
    txt_share_plan: 'Chia sẻ chuyến đi',
    txt_alert_unsuccess: 'Bạn không thể tạo chia sẻ trong lúc này',
    txt_ask_permission_location: 'Ứng dụng cần quyền truy cập vị trí',
    txt_subtitle_permission: 'Ứng dụng cần quyền vị trí của bạn để có thể kết nối với mọi người',
    txt_cancle: 'Không',
    txt_setting: 'Cài đặt',
  },
  ShowNotifyScreen: {
    txt_top_bar_title: 'Thông báo',
    txt_content: 'Nội dung',
    txt_notifi: 'Thông báo',
  },
  TransactionScreen: {
    txt_top_bar_title: 'Lịch sử',
    txt_emty: 'Lịch sử trống',
  },
  UserProfile: {
    txt_top_bar_title: 'Tài khoản',
    txt_edit_account: 'Chỉnh sửa tài khoản',
    txt_available_point: 'Số điểm hiện có',
    txt_point: 'Điểm',
    txt_usage_point_history: 'Lịch sử dùng điểm',
    txt_change_language: 'Thay đổi ngôn ngữ',
    txt_back_to_123Xe: 'Đăng xuất',
    txt_ask_log_out: 'Bạn có chắc chắn muốn đăng xuất?',
    txt_yes: 'Có',
    txt_no: 'Không',
  },
  NavigationController: {
    txt_home_page: 'Trang chủ',
    txt_history: 'Lịch sử',
    txt_account: 'Tài khoản',
    txt_quest: 'Nhiệm vụ',
  },
  MisssionScreen: {
    txt_top_bar_title: 'Nhiệm vụ',
    txt_quest_null: 'Hiện tại bạn không có nhiệm vụ nào',
  },
  QuestItemScreen: {
    txt_daily: 'Nhiệm vụ hàng ngày',
    txt_monthly: 'Nhiệm vụ hàng tháng',
    txt_weekly: 'Nhiệm vụ hàng tuần',
    txt_Yearly: 'Nhiệm vụ hàng năm',
    txt_from: 'Từ',
    txt_to: 'đến',
    txt_received: 'Đã nhận thưởng',
    txt_inprocess: 'Đang tiến hành',
    txt_finished: 'Đã hoàn thành',
    txt_time: 'Thời gian:',
    txt_reward: 'Phần thưởng:',
    txt_point: 'Điểm',
    txt_status: 'Trạng thái',
    txt_detail: 'Xem chi tiết',
  },
  DetailQuestScreen: {
    txt_top_bar_title: 'Chi tiết nhiệm vụ',
    txt_times: 'lần',
    txt_point: 'Điểm',
    txt_login: '- Đăng nhập',
    txt_create: '- Tạo yêu cầu đi nhờ',
    txt_share_plan: '- Chia sẻ chuyến đi',
    txt_use: '- Sử dụng',
    txt_login_number: 'Số lần đăng nhập',
    txt_trip_number: 'Số chuyến đã đi nhờ',
    txt_share_plan_number: 'Số chuyến đã chia sẻ',
    txt_point_number: 'Số điểm đã sử dụng',
    txt_require: 'Yêu cầu: ',
    txt_process: 'Tiến trình nhiệm vụ',
    txt_get_reward: 'Nhận thưởng',
  },
  Start_Screen: {
    txt_top_bar_title: 'Green Move',
    txt_cancel_share_plan: 'Bạn có chắc muốn huỷ chia sẻ này ?',
    txt_comfirm: 'Đồng ý',
    txt_cancel: 'Không',
    txt_back_to_123xe: 'Bạn có chắc chắn muốn trở lại 123xe?',
    txt_account: 'Tài khoản',
    txt_point: 'Điểm',
    txt_notification: 'Thông báo:',
    txt_on: 'Bật',
    txt_off: 'Tắt',
    txt_your_plan: 'Chuyến đang chia sẻ',
    txt_dont_have_plan:
      'Bạn chưa có kế hoạch di chuyển của mình. Vui lòng cập nhật kế hoạch của mình để có thể chia sẻ với mọi người.',
    txt_let_share: 'Bắt đầu chia sẻ bây giờ',
    txt_share_plan: 'Chia sẻ chuyến đi',
    txt_create_trip: 'Tìm xe đi chung',
    txt_title_ask_permission: 'Bạn cần cho phép quyền vị trí để có thể sử dụng dịch vụ này',
    txt_message: 'Cho phép ngay bây giờ',
    txt_yes: 'Đồng ý',
    txt_no: 'Để sau',
    txt_intro_text: 'Giới thiệu Green Move',
    txt_intro_1: '- Kết nối 2 người có nhu cầu đi lại trên cùng tuyến đường',
    txt_intro_2: 'để đi chung xe máy,',
    txt_intro_3: 'bạn có thể chia sẻ cho người khác đi cùng xe,',
    txt_intro_4: 'được ghi nhận, tích điểm',
    txt_intro_5: 'và sau đó có thể dùng điểm này để đi xe được chia sẻ bởi người khác.',
    txt_target_text: 'Cách hoạt động',
    txt_targer:
      '- Xây dựng cộng đồng chia sẻ xe lớn mạnh nhất Việt Nam.\n- Trở thành một giải pháp về ách tấc giao thông đường bộ trong các thành phố lớn.',

    txt_result_text: 'Kết quả',
    txt_result:
      '- Giảm thiểu chi phí đi lại cho người sử dụng.\n- Giảm thiểu lượng xe lưu thông,giải quyết vấn đề ùn tắc giao thông.\n- Bảo vệ môi trường.',
    txt_disconect: 'Kết nối mạng không ổn định vui lòng kiểm tra lại',
    txt_Creating_trip: 'Chuyến đang đi chung',
    txt_intro_creating:
      'Bạn đang có nhu cầu cần di chuyển ? Hãy sử dụng điểm tích luỹ trong tài khoản để có thể tìm được tài xế của mình ngay nào.',
    txt_find_driver: 'Bắt đầu tìm tài xế ngay',
  },
  SelectLanguage: {
    txt_top_bar_title: 'Thay đổi ngôn ngữ',
    txt_change_language: 'Thay đổi ngôn ngữ',
    txt_change_language_Eng_title: 'Bạn có chắc chắn đổi sang ngôn ngữ English?',
    txt_change_language_Viet_title: 'Bạn có chắc chắn đổi sang ngôn ngữ VietNam?',
    txt_cancle: 'Không',
    txt_comfirm: 'Đồng ý',
  },
  InboxScreen: {
    txt_top_title_bar: 'Hòm thư',
    txt_notify_emty: 'Hòm thư trống!',
  },
};
const stringEn = {
  language: 'en',
  SharePlaneSaga: {
    txt_error_pick:
      'The selected drop-off and pick-up locations are not appropriate. Please select again',
  },
  UserProfileSaga: {
    txt_acount_lock:
      'Your account has been locked. Please contact the operator for further assistance',
    txt_comfirm: 'Agree',
    txt_update_success: 'Update successfully',
  },
  HistorySaga: {
    txt_cancel_trip_success: 'The trip has been canceled successfully',
    txt_send_complain_success: 'The complaint has been sent successfully',
  },
  HandleErrorCode: {
    txt_haveTrip: 'You are taking another trip. Please try again when the trip ends',
    txt_unknow_error: 'There was an error (Unknown error)',
    txt_param_error: 'There was an error (Parram error)',
    txt_data_nil: 'No data',
    txt_request_fail: 'Request failed please try again',
    txt_not_enough_money: `You don't have enough points to make this request`,
    txt_account_not_exsist: 'This account does not exist',
    txt_system_error: 'System error please try again later',
    txt_session_expired: 'The login session has expired, please log in again',
  },
  PlanItem: {
    txt_finding: 'Find the appropriate request',
    txt_cancel_plan: 'Cancel sharing',
    txt_show_detail: 'View details',
    txt_share: 'You are sharing a trip',
  },
  HistoryItem: {
    txt_trip_cancel: 'The trip has been canceled',
    txt_find_driver: 'Find driver',
    txt_driver_pick_up: 'The driver is coming to pick you up',
    txt_passenger_wait: 'Passengers are waiting for you to pick up',
    txt_running: 'The trip is running',
    txt_trip_finished: 'The trip has ended',
    txt_point: 'Point',
    txt_share: 'Share',
    txt_hitchhike: 'Hitchhike',
  },
  CreateTrip: {
    txt_select_origin: 'Select your pick-up location',
    txt_input_origin: 'Enter your pick-up location. . . ',
    txt_select_with_map: 'Select with map',
    txt_put_origin: 'Set your pick-up location',
    txt_put_destination: 'Set your destination',
    txt_input_destination: 'Enter your destination. . . ',
    txt_origin: 'Pick up location',
    txt_destination: 'Destination',
    txt_point_to_usage: 'Point to use',
    txt_point: 'Point',
    txt_find_driver: 'Find driver',
    txt_ask_where_go: 'Where do you want to go?',
  },
  DetailTripScreen: {
    txt_top_bar_title: 'Details',
    txt_cancel_trip: 'Are you sure you want to cancel this trip?',
    txt_cancel: 'No',
    txt_comfirm: 'Agree',
    txt_cancel_trip_noDriver: 'Are you sure you want to send this report?',
    txt_passenger_cancel: 'Passengers request to cancel the trip',
    txt_Driver_busy: `I am busy so I can't come to pick up passengers`,
    txt_other_reason: 'Other reasons',
    txt_Driver_cancel: 'The driver tells me to cancel',
    txt_Passenger_no_need: 'I have no need',
    txt_origin: 'Pick up location',
    txt_destination: 'Destination',
    txt_detail_trip: 'Details of the trip',
    txt_trip_thanks: '(Hitchhiking Trip)',
    txt_sharing_trip: '(Sharing trip)',
    txt_point_usage: 'Point Usage',
    txt_point: 'Point',
    txt_distance: 'Distance',
    txt_find_sharers: '. . . Looking for sharers',
    txt_cancel_trip_act: 'Cancel the trip',
    txt_trip_was_cancel: 'This trip has been canceled',
    txt_agree: 'has agreed to let you hitchhike. The sharer will contact you within a few minutes',
    txt_name: 'Full name',
    txt_phone: 'Phone number',
    txt_liecense_plate: 'License plate',
    txt_agree_to: 'You have agreed to let',
    txt_hitchhike: 'Hitchhike',
    txt_take_passenger: 'Pick up passengers',
    txt_trip_was_finish: 'The trip has ended',
    txt_report: 'Report the trip',
    txt_finishTrip: 'Drop off passengers',
    txt_shared_a_trip: 'has shared a trip with you',
    txt_running_with: 'You are taking the trip with',
    txt_send_complain: 'Submit a complaint',
    txt_content: 'Content',
    txt_reason: 'Cancellation reasons',
    txt_place_holder_reason: 'Choose a reason for cancellation. . . ',
    txt_request_cancel_trip: 'Request to cancel the trip',
  },
  DetailUserProfileScreen: {
    txt_top_bar_title: 'Account information',
    txt_point: 'Point',
    txt_name: 'Full name',
    txt_phone: 'Phone number',
    txt_liecense_plate: 'License plate',
    txt_vehicle_name: 'Vehicle name',
    txt_save: 'Save information',
    txt_camera: 'Camera',
    txt_library: 'Select from library',
    txt_cancel: 'Cancel',
  },
  HistoryScreen: {
    txt_top_bar_title: 'History',
    txt_empty: 'You have not booked a trip yet',
  },
  PendingTripScreen: {
    txt_top_bar_title: 'Do you want to take this trip?',
    txt_ask: 'Are you sure you want to share the trip with this person?',
    txt_comfirm: 'Agree',
    txt_cancel: 'No',
    txt_time: 'Time',
    txt_name: 'Full name:',
    txt_distance: 'Distance:',
    txt_point_take: 'Received points:',
    txt_point: 'Point',
    txt_take_trip: 'Take the trip',
    txt_later: 'Later',
    txt_trip_has_driver: 'The trip has another driver',
    txt_trip_cancel: 'The trip has been canceled',
    txt_trip_finish: 'The trip has ended',
  },
  SearchTripSceen: {
    txt_top_bar_title: 'Search requests',
    txt_finding: 'Searching for a suitable trip. . . ',
  },
  SharePlanScreen: {
    txt_infomation_about_car: 'You have no information about the vehicle. Please update here',
    txt_update: 'Update now',
    txt_later: 'Later',
    txt_select_origin: 'Select your pick-up location',
    txt_input_origin: 'Enter your pick-up location. . . ',
    txt_select_with_map: 'Select with map',
    txt_put_origin: 'Set your pick-up location',
    txt_put_destination: 'Set your destination',
    txt_select_destination: 'Select your destination',
    txt_input_destination: 'Enter your destination. . . ',
    txt_title_step_comfirm: 'Green-Move',
    txt_origin: 'Pick-up location',
    txt_destination: 'Destination',
    txt_point_to_use: 'Point to use',
    txt_point: 'Point',
    txt_share_plan: 'Share the trip',
    txt_alert_unsuccess: 'You cannot share at the moment',
    txt_ask_permission_location: 'Can we access your photos?',
    txt_subtitle_permission: 'We need access to connect everyone',
    txt_cancle: 'No',
    txt_setting: 'Open Settings',
  },
  ShowNotifyScreen: {
    txt_top_bar_title: 'Notifications',
    txt_content: 'Content',
    txt_notifi: 'Notifications',
  },
  TransactionScreen: {
    txt_top_bar_title: 'History',
    txt_emty: 'History is empty',
  },
  UserProfile: {
    txt_top_bar_title: 'Account',
    txt_edit_account: 'Edit account',
    txt_available_point: 'Available points',
    txt_point: 'Point',
    txt_usage_point_history: 'Point usage history',
    txt_change_language: 'Change language',
    txt_back_to_123Xe: 'Log out',
    txt_ask_log_out: 'Are you sure want to log out?',
    txt_yes: 'Yes',
    txt_no: 'No',
  },
  NavigationController: {
    txt_home_page: 'Home',
    txt_history: 'History',
    txt_account: 'Account',
    txt_quest: 'Task',
  },
  MisssionScreen: {
    txt_top_bar_title: 'Tasks',
    txt_quest_null: 'You have no tasks at the moment',
  },
  QuestItemScreen: {
    txt_daily: 'Daily tasks',
    txt_monthly: 'Monthly tasks',
    txt_weekly: 'Weekly tasks',
    txt_Yearly: 'Annual tasks',
    txt_from: 'From',
    txt_to: 'To',
    txt_received: 'Reward received',
    txt_inprocess: 'In progress',
    txt_finished: 'Finished',
    txt_time: 'Time:',
    txt_reward: 'Reward:',
    txt_point: 'Point',
    txt_status: 'Status',
    txt_detail: 'View details',
  },
  DetailQuestScreen: {
    txt_top_bar_title: 'Task details',
    txt_times: 'Times',
    txt_point: 'Point',
    txt_login: '- Login',
    txt_create: '- Create a hitchhiking request',
    txt_share_plan: '- Share the trip',
    txt_use: '- Use',
    txt_login_number: 'Number of logins',
    txt_trip_number: 'Number of hitchhiking trips',
    txt_share_plan_number: 'Number of sharing trips',
    txt_point_number: 'Number of points used',
    txt_require: 'Require:',
    txt_process: 'Task progress',
    txt_get_reward: 'Get rewarded',
  },
  Start_Screen: {
    txt_top_bar_title: 'Green Move',
    txt_cancel_share_plan: 'Are you sure you want to cancel sharing?',
    txt_comfirm: 'Agree',
    txt_cancel: 'No',
    txt_back_to_123xe: 'Are you sure you want to go back to 123xe?',
    txt_account: 'Account',
    txt_point: 'Point',
    txt_notification: 'Notification:',
    txt_on: 'On',
    txt_off: 'Off',
    txt_your_plan: 'The trip is shared',
    txt_dont_have_plan:
      'You haven’t had a plan for the trip yet. Please update your plan so that you can share it with everyone.',
    txt_let_share: 'Start sharing now',
    txt_share_plan: 'Share the trip',
    txt_create_trip: 'Find trip together',
    txt_title_ask_permission: 'You need to give location permissions to use this service',
    txt_message: 'Allow now',
    txt_yes: 'Agree',
    txt_no: 'Later',
    txt_intro_text: 'Introducing Green Move',
    txt_intro_1: '- Connect two people who need to travel on the same route',
    txt_intro_2: 'to share a motorbike,',
    txt_intro_3: 'you can share it with other people,',
    txt_intro_4: 'Be recognized, earn points',
    txt_intro_5: 'and then you can use these points to hitchhike others.',
    txt_target_text: 'How it works',
    txt_targer:
      '- Build the largest vehicle sharing community in Vietnam.\n- Become a solution to traffic congestion in big cities.',

    txt_result_text: 'Result',
    txt_result: `- Minimize travel costs for users.\n- Minimize traffic volume, hence solve traffic congestion problem.\n- Protect the environment. `,
    txt_disconect: 'Network connection is not stable please check again',
    txt_Creating_trip: 'You are going together on a trip',
    txt_intro_creating:
      'Are you in need of travelling? Use the points accumulated in your account to find your driver right now.',
    txt_find_driver: 'Start searching for drivers now',
  },
  SelectLanguage: {
    txt_top_bar_title: 'Change language',
    txt_change_language: 'Change language',
    txt_change_language_Eng_title: 'Are you sure you want to change to English?',
    txt_change_language_Viet_title: 'Are you sure you want to change to Vietnamese language?',
    txt_cancle: 'No',
    txt_comfirm: 'Agree',
  },
  InboxScreen: {
    txt_top_title_bar: 'Inbox',
    txt_notify_emty: 'No messages now!',
  },
};
let currLangID = 'vi';
let currentLanguageString = {};
Object.assign(currentLanguageString, stringVi);
export function updateLocale(currentLanguage) {
  // const currentLanguage =  store.getState().language.locale;
  // console.log(store.getState().language.locale);
  if (currLangID === currentLanguage) {
    return currentLanguageString;
  }
  console.log('language update', currentLanguage);
  currLangID = currentLanguage;

  const newLang = {};
  currentLanguageString = newLang;
  switch (currentLanguage) {
    case 'en':
      Object.assign(newLang, stringEn);
      Object.assign(getLocalLanguage, newLang);
      return newLang;
    case 'vi':
      Object.assign(newLang, stringVi);
      Object.assign(getLocalLanguage, newLang);
      return newLang;
    case 'cn':
      Object.assign(newLang, stringCn);
      Object.assign(getLocalLanguage, newLang);
      return newLang;
    default:
      return currentLanguageString;
  }
}
function getLocalLanguage() {
  return currentLanguageString;
}
Object.assign(getLocalLanguage, stringVi);

export default getLocalLanguage; // currentLanguageString;
